#!/usr/bin/env bash

ROOT_DIR=$(readlink -f $(dirname $0))
execBin="$ROOT_DIR/gui/dist/electron-app-1.0.0.AppImage"
if [ -x "$execBin" ]; then
  "$execBin"
  exit
fi
cd "$ROOT_DIR/gui" || exit
npm run start
